export const mockSuppliers = [
    {
      id: 1,
      name: "FastShip Co",
      contact_info: "fast@ship.com",
      reliability_score: 0.85,
    },
    {
      id: 2,
      name: "MegaLogistics",
      contact_info: "mega@logistics.com",
      reliability_score: 0.60,
    },
    {
      id: 3,
      name: "QuickFreight",
      contact_info: "quick@freight.com",
      reliability_score: 0.35,
    },
    {
      id: 4,
      name: "AsiaTrade Ltd",
      contact_info: "asia@trade.com",
      reliability_score: 0.75,
    },
    {
      id: 5,
      name: "GlobalMove",
      contact_info: "global@move.com",
      reliability_score: 0.45,
    },
  ]
  
  export const mockShipments = [
    {
      id: 1,
      supplier_id: 1,
      supplier_name: "FastShip Co",
      origin: "Shanghai",
      destination: "Kuala Lumpur",
      date_sent: "2024-01-01",
      date_expected: "2024-01-15",
      status: "delivered",
      risk_score: 0.12,
    },
    {
      id: 2,
      supplier_id: 2,
      supplier_name: "MegaLogistics",
      origin: "Jakarta",
      destination: "Penang",
      date_sent: "2024-01-05",
      date_expected: "2024-01-20",
      status: "in_transit",
      risk_score: 0.45,
    },
    {
      id: 3,
      supplier_id: 3,
      supplier_name: "QuickFreight",
      origin: "Guangzhou",
      destination: "Johor Bahru",
      date_sent: "2024-01-08",
      date_expected: "2024-01-18",
      status: "delayed",
      risk_score: 0.78,
    },
    {
      id: 4,
      supplier_id: 4,
      supplier_name: "AsiaTrade Ltd",
      origin: "Bangkok",
      destination: "Kuala Lumpur",
      date_sent: "2024-01-10",
      date_expected: "2024-01-22",
      status: "in_transit",
      risk_score: 0.30,
    },
    {
      id: 5,
      supplier_id: 5,
      supplier_name: "GlobalMove",
      origin: "Singapore",
      destination: "Penang",
      date_sent: "2024-01-12",
      date_expected: "2024-01-19",
      status: "delayed",
      risk_score: 0.65,
    },
  ]
  
  export const mockStats = {
    totalSuppliers:   5,
    totalShipments:   5,
    highRiskCount:    1,
    mediumRiskCount:  2,
    lowRiskCount:     2,
    avgRiskScore:     0.46,
  }